project:
  type: website
  output-dir: docs

website:
  title: "Lucia Murillo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About me
        href: about.qmd
      - text: Hobbies
        href: hobbies.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd 

format:
  html:
    theme: styles.scss
    mainfont: "Noto Serif"
    toc: true
    page-layout: full
links:
    - icon: linkedin 
      text: LinkedIn
      href: www.linkedin.com/in/lucia-murillo-34b604240
      target: _blank
    - icon: github
      text: GitHub
      href: https://github.com/lucia-murillo
      target: _blank
    - icon: envelope
      text: Email
      href: mailto:luciaviola@gmail.com
      




