project:
  type: website
  output-dir: docs

website:
  title: "Lucia Murillo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hobbies.qmd
      - projects.qmd
      - resume.qmd 

format:
  html:
    theme: 
    - morph 
    - brand
    - styles.scss
    mainfont: Noto Serif
    toc: true
    page-layout: full 



